# Generated by Django 5.0.1 on 2024-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbStatusambilbarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_column='TANGGAL')),
                ('nama', models.CharField(db_column='NAMA', max_length=25)),
                ('departemen', models.CharField(db_column='DEPARTEMEN', max_length=20)),
                ('nama_barang', models.CharField(db_column='NAMA_BARANG', max_length=20)),
                ('jumlah', models.IntegerField(db_column='JUMLAH')),
                ('satuan', models.CharField(db_column='SATUAN', max_length=10)),
                ('keterangan', models.TextField(db_column='KETERANGAN')),
            ],
            options={
                'db_table': 'tb_statusambilbarang',
                'managed': False,
            },
        ),
    ]
