# Generated by Django 5.0.1 on 2024-01-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengambilanbarang', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbStatusambilbarang',
        ),
    ]
