# Generated by Django 5.0.1 on 2024-01-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengambilanbarang', '0002_delete_tbstatusambilbarang'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbAmbilbarangform',
            fields=[
                ('no_ambil', models.AutoField(db_column='NO_AMBIL', primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(db_column='TANGGAL')),
                ('departemen', models.CharField(db_column='DEPARTEMEN', max_length=20)),
                ('gambar_serah', models.TextField(blank=True, db_column='GAMBAR_SERAH', null=True)),
                ('gambar_dokum', models.TextField(blank=True, db_column='GAMBAR_DOKUM', null=True)),
                ('keterangan_pengambil', models.TextField(blank=True, db_column='KETERANGAN_PENGAMBIL', null=True)),
                ('keterangan_admin', models.TextField(blank=True, db_column='KETERANGAN_ADMIN', null=True)),
            ],
            options={
                'db_table': 'tb_ambilbarangform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbAmbilbarangket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(db_column='NAMA_BARANG', max_length=20)),
                ('jumlah', models.IntegerField(db_column='JUMLAH')),
                ('satuan', models.CharField(blank=True, db_column='SATUAN', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tb_ambilbarangket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=11, primary_key=True, serialize=False)),
                ('nama_user', models.CharField(db_column='NAMA_USER', max_length=25)),
                ('password', models.CharField(db_column='PASSWORD', max_length=8)),
                ('jabatan', models.CharField(db_column='JABATAN', max_length=25)),
                ('departemen', models.CharField(db_column='DEPARTEMEN', max_length=25)),
            ],
            options={
                'db_table': 'tb_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUserdetail',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tempat_lahir', models.CharField(blank=True, db_column='TEMPAT_LAHIR', max_length=25, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, db_column='TANGGAL_LAHIR', null=True)),
                ('alamat', models.CharField(blank=True, db_column='ALAMAT', max_length=50, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, db_column='JENIS_KELAMIN', max_length=6, null=True)),
                ('nik', models.CharField(blank=True, db_column='NIK', max_length=25, null=True)),
                ('tanggal_masuk', models.DateField(blank=True, db_column='TANGGAL_MASUK', null=True)),
                ('e_mail', models.CharField(blank=True, db_column='E-MAIL', max_length=25, null=True)),
                ('foto_user', models.TextField(blank=True, db_column='FOTO_USER', null=True)),
            ],
            options={
                'db_table': 'tb_userdetail',
                'managed': False,
            },
        ),
    ]
